import { api, newIdempotencyKey } from '@/services/apiClient'
import { readJson, StorageKeys, writeJson } from '@/lib/storage'
import type {
  CartLineRequest,
  CartQuoteDto,
  GuestSession,
  MenuDto,
  OrderDto,
} from '@/types/api'

const guest = { tokenKind: 'guest' } as const

export function storedGuestSession(): GuestSession | null {
  const session = readJson<GuestSession>(StorageKeys.guestSession)
  if (!session) return null
  return new Date(session.expiresAt) > new Date() ? session : null
}

/** Scanning the code on the table. The only anonymous call in the app. */
export async function resolveQrToken(token: string): Promise<GuestSession> {
  const session = await api.get<GuestSession>(`/api/v1/public/qr/${encodeURIComponent(token)}`, {
    tokenKind: 'guest',
  })

  writeJson(StorageKeys.guestSession, session)
  return session
}

export function fetchGuestMenu(): Promise<MenuDto> {
  return api.get<MenuDto>('/api/v1/public/menu', guest)
}

/**
 * The only total that counts.
 *
 * The cart's own arithmetic is a preview so the screen can react instantly; this
 * is what the guest is actually asked to agree to.
 */
export function priceCart(lines: CartLineRequest[]): Promise<CartQuoteDto> {
  return api.post<CartQuoteDto>('/api/v1/public/cart/price', { lines }, guest)
}

/**
 * Sends the order.
 *
 * The idempotency key is generated by the caller and reused on every retry of
 * the same tap, so a guest on weak 4G who presses twice gets one order.
 */
export function placeGuestOrder(
  lines: CartLineRequest[],
  notes: string | undefined,
  idempotencyKey: string,
): Promise<OrderDto> {
  return api.post<OrderDto>(
    '/api/v1/public/orders',
    { lines, notes },
    { ...guest, idempotencyKey },
  )
}

export function fetchMySession(): Promise<{
  tableSessionId: string
  tableId: string
  orders: OrderDto[]
  total: number
}> {
  return api.get('/api/v1/public/session', guest)
}

export function callWaiter(): Promise<void> {
  return api.post('/api/v1/public/session/call-waiter', undefined, guest)
}

export function requestBill(): Promise<void> {
  return api.post('/api/v1/public/session/request-bill', undefined, guest)
}

export { newIdempotencyKey }
