<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>STED.RestaurantOS.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\STED.RestaurantOS.Domain\STED.RestaurantOS.Domain.csproj" />
    <ProjectReference Include="..\STED.RestaurantOS.Shared\STED.RestaurantOS.Shared.csproj" />
  </ItemGroup>

</Project>
