<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Teachers, students and guardians.
 *
 * Each of the three is a profile row that *may* be linked to a `users` row.
 * A student without a login is still a full student record; the account is an
 * optional attachment, not a prerequisite.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('teachers', function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->foreignUuid('school_id')->constrained('schools')->cascadeOnDelete();
            $table->foreignUuid('user_id')->nullable()->constrained('users')->nullOnDelete();

            $table->string('employee_number', 40);
            $table->string('first_name', 120);
            $table->string('last_name', 120);
            $table->string('gender', 16)->nullable();
            $table->date('birth_date')->nullable();
            $table->string('email')->nullable();
            $table->string('phone', 40)->nullable();
            $table->string('address')->nullable();
            $table->string('photo_path')->nullable();

            $table->string('specialty', 120)->nullable();
            $table->string('qualification', 160)->nullable();
            $table->date('hired_on')->nullable();
            // active | on_leave | inactive
            $table->string('status', 24)->default('active');

            $table->timestamps();
            $table->softDeletes();

            $table->unique(['school_id', 'employee_number']);
            $table->index(['school_id', 'status']);
            $table->index(['school_id', 'last_name']);
        });

        Schema::create('guardians', function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->foreignUuid('school_id')->constrained('schools')->cascadeOnDelete();
            $table->foreignUuid('user_id')->nullable()->constrained('users')->nullOnDelete();

            $table->string('first_name', 120);
            $table->string('last_name', 120);
            $table->string('gender', 16)->nullable();
            $table->string('email')->nullable();
            $table->string('phone', 40)->nullable();
            $table->string('phone_alt', 40)->nullable();
            $table->string('address')->nullable();
            $table->string('occupation', 120)->nullable();
            $table->string('national_id', 60)->nullable();

            // Preferred channel for this guardian's notifications.
            $table->string('preferred_channel', 16)->default('email');

            $table->timestamps();
            $table->softDeletes();

            $table->index(['school_id', 'last_name']);
            $table->index(['school_id', 'phone']);
        });

        Schema::create('students', function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->foreignUuid('school_id')->constrained('schools')->cascadeOnDelete();
            $table->foreignUuid('user_id')->nullable()->constrained('users')->nullOnDelete();

            // Generated by MatriculeGenerator; unique inside the tenant.
            $table->string('matricule', 40);

            $table->string('first_name', 120);
            $table->string('last_name', 120);
            $table->string('middle_name', 120)->nullable();
            $table->string('gender', 16)->nullable();
            $table->date('birth_date')->nullable();
            $table->string('birth_place', 160)->nullable();
            $table->string('nationality', 80)->nullable();

            $table->string('email')->nullable();
            $table->string('phone', 40)->nullable();
            $table->string('address')->nullable();
            $table->string('photo_path')->nullable();

            $table->string('blood_group', 8)->nullable();
            $table->text('medical_notes')->nullable();

            $table->string('emergency_contact_name', 160)->nullable();
            $table->string('emergency_contact_phone', 40)->nullable();
            $table->string('emergency_contact_relation', 60)->nullable();

            // active | graduated | transferred | withdrawn | archived
            $table->string('status', 24)->default('active');
            $table->date('enrolled_on')->nullable();
            $table->date('left_on')->nullable();
            $table->string('previous_school', 160)->nullable();

            $table->timestamps();
            $table->softDeletes();

            $table->unique(['school_id', 'matricule']);
            $table->index(['school_id', 'status']);
            $table->index(['school_id', 'last_name', 'first_name']);
        });

        // A student may have several guardians; a guardian several students.
        Schema::create('student_guardian', function (Blueprint $table): void {
            $table->foreignUuid('student_id')->constrained('students')->cascadeOnDelete();
            $table->foreignUuid('guardian_id')->constrained('guardians')->cascadeOnDelete();
            $table->foreignUuid('school_id')->constrained('schools')->cascadeOnDelete();

            $table->string('relationship', 40);         // mother | father | tutor | other
            // The guardian who receives invoices and is legally responsible.
            $table->boolean('is_primary')->default(false);
            $table->boolean('is_financial_responsible')->default(false);
            $table->boolean('can_pick_up')->default(true);

            $table->timestamps();

            $table->primary(['student_id', 'guardian_id']);
            $table->index('school_id');
        });

        // A student's placement in a class for a given academic year. History
        // is preserved: one row per year, never overwritten.
        Schema::create('enrollments', function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->foreignUuid('school_id')->constrained('schools')->cascadeOnDelete();
            $table->foreignUuid('student_id')->constrained('students')->cascadeOnDelete();
            $table->foreignUuid('academic_year_id')->constrained('academic_years')->cascadeOnDelete();
            $table->foreignUuid('school_class_id')->constrained('school_classes')->restrictOnDelete();

            $table->date('enrolled_on');
            $table->date('ended_on')->nullable();
            // active | completed | transferred | withdrawn
            $table->string('status', 24)->default('active');
            // new_admission | re_enrollment | transfer_in
            $table->string('enrollment_type', 24)->default('new_admission');
            $table->text('notes')->nullable();

            $table->timestamps();

            // A student sits in exactly one class per academic year.
            $table->unique(['student_id', 'academic_year_id']);
            $table->index(['school_id', 'school_class_id', 'status']);
        });

        // Which teacher teaches which subject to which class, and with what
        // coefficient. This is the row the grade policy checks.
        Schema::create('class_subjects', function (Blueprint $table): void {
            $table->uuid('id')->primary();
            $table->foreignUuid('school_id')->constrained('schools')->cascadeOnDelete();
            $table->foreignUuid('school_class_id')->constrained('school_classes')->cascadeOnDelete();
            $table->foreignUuid('subject_id')->constrained('subjects')->cascadeOnDelete();
            $table->foreignUuid('teacher_id')->nullable()->constrained('teachers')->nullOnDelete();

            $table->decimal('coefficient', 5, 2)->default(1);
            $table->unsignedSmallInteger('weekly_hours')->nullable();
            $table->boolean('is_active')->default(true);

            $table->timestamps();

            $table->unique(['school_class_id', 'subject_id']);
            $table->index(['school_id', 'teacher_id']);
        });

        // Homeroom teacher FK is added here, once `teachers` exists.
        Schema::table('school_classes', function (Blueprint $table): void {
            $table->foreign('homeroom_teacher_id')->references('id')->on('teachers')->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::table('school_classes', function (Blueprint $table): void {
            $table->dropForeign(['homeroom_teacher_id']);
        });
        Schema::dropIfExists('class_subjects');
        Schema::dropIfExists('enrollments');
        Schema::dropIfExists('student_guardian');
        Schema::dropIfExists('students');
        Schema::dropIfExists('guardians');
        Schema::dropIfExists('teachers');
    }
};
